import { AgeEnum } from "./AgeEnum";
import { AnimEnum } from "./AnimEnum";
import { EntityConstants } from "./EntityConstants";
import { TypeEnum } from "./TypeEnum";

export const AGE_TYPE: Record<AgeEnum, TypeEnum[]> = {
    [AgeEnum.ONE]: [TypeEnum.ONE_SHORT, TypeEnum.ONE_LONG, TypeEnum.ONE_TANK],
    [AgeEnum.TWO]: [TypeEnum.TWO_SHORT, TypeEnum.TWO_LONG, TypeEnum.TWO_TANK],
    [AgeEnum.THREE]: [
        TypeEnum.THREE_SHORT,
        TypeEnum.THREE_LONG,
        TypeEnum.THREE_TANK,
    ],
    [AgeEnum.FOUR]: [
        TypeEnum.FOUR_SHORT,
        TypeEnum.FOUR_LONG,
        TypeEnum.FOUR_TANK,
    ],
    [AgeEnum.FIVE]: [
        TypeEnum.FIVE_SHORT,
        TypeEnum.FIVE_LONG,
        TypeEnum.FIVE_TANK,
        TypeEnum.FIVE_SPECIAL,
    ],
};

export const TYPE_DATA: Record<TypeEnum, EntityConstants> = {
    [TypeEnum.ONE_SHORT]: {
        name: "",
        cost: 15,
        build_time: 1000,
        gain: 30,
        maxHp: 20,
        width: 5,
        range: 5,
        attack: 5,
        attack_time: 1000,
        speed: 5,
    },
    [TypeEnum.ONE_LONG]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.ONE_TANK]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.TWO_SHORT]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.TWO_LONG]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.TWO_TANK]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.THREE_SHORT]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.THREE_LONG]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.THREE_TANK]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.FOUR_SHORT]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.FOUR_LONG]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.FOUR_TANK]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.FIVE_SHORT]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.FIVE_LONG]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.FIVE_TANK]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
    [TypeEnum.FIVE_SPECIAL]: {
        name: "",
        cost: 0,
        build_time: 0,
        gain: 0,
        maxHp: 0,
        width: 0,
        range: 0,
        attack: 0,
        attack_time: 0,
        speed: 0,
    },
};
